package com.voudeonibus.event;


public enum MessageEvent {

    HIDE_SIDEBAR,
    SHOW_SIDEBAR,
    UPDATE_CATEGORY,
    UPDATE_LINES,
    UPDATE_VOU_AGORA,
    UPDATE_FACEBOOK_PROFILE,
    SHOW_FACEBOOK_PROFILE,
    HIDE_FACEBOOK_PROFILE,
    UPDATE_WEATHER,
    SHOW_CHOICE_CATEGORY,
    HIDE_CHOICE_CATEGORY,
    SHOW_NOTIFICATION,
    HIDE_NOTIFICATION,
    SHOW_NOTIFICATION_BTN_CLEAR,
    HIDE_NOTIFICATION_BTN_CLEAR,
    SHOW_CATEGORY_TUTORIAL,
    HIDE_CATEGORY_TUTORIAL,
    REVERSE_BACKGROUND,
    APPLY_BACKGROUND_DEFAULT,
    APPLY_BG_LEVEL_0,
    APPLY_BG_LEVEL_1,
    APPLY_BG_LEVEL_2,
    APPLY_BG_LEVEL_3,
    OPEN_LOADING,
    CLOSE_LOADING,
    GET_VIEW,
    SWITCH_ALL_LINES,
    SWITCH_VOU_AGORA


}
